// <auto-generated />
using System;
using DrinkItUpWebApp.DAL.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrinkItUpWebApp.DAL.Migrations
{
    [DbContext(typeof(DrinkContext))]
    [Migration("20230522161907_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DrinkItUpWebApp.DAL.Entities.Difficulty", b =>
                {
                    b.Property<int>("DifficultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DifficultyId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("DifficultyId");

                    b.ToTable("Difficulties");
                });

            modelBuilder.Entity("DrinkItUpWebApp.DAL.Entities.Drink", b =>
                {
                    b.Property<int>("DrinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrinkId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DifficultyId")
                        .HasColumnType("int");

                    b.Property<int>("MainAlcoholId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DrinkId");

                    b.HasIndex("DifficultyId")
                        .IsUnique();

                    b.HasIndex("MainAlcoholId")
                        .IsUnique();

                    b.ToTable("Drinks");
                });

            modelBuilder.Entity("DrinkItUpWebApp.DAL.Entities.DrinkIngredient", b =>
                {
                    b.Property<int>("DrinkId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DrinkId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("DrinkIngredients");
                });

            modelBuilder.Entity("DrinkItUpWebApp.DAL.Entities.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("IngredientId");

                    b.HasIndex("UnitId")
                        .IsUnique();

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("DrinkItUpWebApp.DAL.Entities.MainAlcohol", b =>
                {
                    b.Property<int>("MainAlcoholId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MainAlcoholId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("MainAlcoholId");

                    b.ToTable("MainAlcohols");
                });

            modelBuilder.Entity("DrinkItUpWebApp.DAL.Entities.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("UnitId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("DrinkItUpWebApp.DAL.Entities.Drink", b =>
                {
                    b.HasOne("DrinkItUpWebApp.DAL.Entities.Difficulty", "Difficulty")
                        .WithOne("Drink")
                        .HasForeignKey("DrinkItUpWebApp.DAL.Entities.Drink", "DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrinkItUpWebApp.DAL.Entities.MainAlcohol", "MainAlcohol")
                        .WithOne("Drink")
                        .HasForeignKey("DrinkItUpWebApp.DAL.Entities.Drink", "MainAlcoholId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("MainAlcohol");
                });

            modelBuilder.Entity("DrinkItUpWebApp.DAL.Entities.DrinkIngredient", b =>
                {
                    b.HasOne("DrinkItUpWebApp.DAL.Entities.Drink", "Drink")
                        .WithMany("DrinkIngredients")
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrinkItUpWebApp.DAL.Entities.Ingredient", "Ingredient")
                        .WithMany("DrinkIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drink");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("DrinkItUpWebApp.DAL.Entities.Ingredient", b =>
                {
                    b.HasOne("DrinkItUpWebApp.DAL.Entities.Unit", "Unit")
                        .WithOne("Ingredient")
                        .HasForeignKey("DrinkItUpWebApp.DAL.Entities.Ingredient", "UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("DrinkItUpWebApp.DAL.Entities.Difficulty", b =>
                {
                    b.Navigation("Drink");
                });

            modelBuilder.Entity("DrinkItUpWebApp.DAL.Entities.Drink", b =>
                {
                    b.Navigation("DrinkIngredients");
                });

            modelBuilder.Entity("DrinkItUpWebApp.DAL.Entities.Ingredient", b =>
                {
                    b.Navigation("DrinkIngredients");
                });

            modelBuilder.Entity("DrinkItUpWebApp.DAL.Entities.MainAlcohol", b =>
                {
                    b.Navigation("Drink");
                });

            modelBuilder.Entity("DrinkItUpWebApp.DAL.Entities.Unit", b =>
                {
                    b.Navigation("Ingredient");
                });
#pragma warning restore 612, 618
        }
    }
}
